### ISSUE TITLE
Raspberry Pico

### ISSUE THREAD

**Issue by varna9000** [dafvid/micropython-bmp280#1] opened 2021-03-07 06:38 UTC
Hi, I get the following error when using the example code in RPi Pico:

`Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "bmp280.py", line 97, in __init__
  File "bmp280.py", line 126, in _read
OSError: 5`

The bmp280 is visible with i2c.scan()

Also the example code should have 
`import bmp280`

otherwise the variables are not loaded, only the class.

**Comment by dafvid** [comment] 2021-03-07 06:53
Hi!
Try and look at https://forum.micropython.org/viewtopic.php?t=4746
Seems the eeprom might not be ready yet. Try to add a short (100 ms) pause between initiation and first read. Depending on how you power it it might need some time to "warm up" before any reading.

**Comment by varna9000** [comment] 2021-03-07 07:38
Got it working with the minimal example below. Apparently I was not using your example code right, and also I imported the whole module, not just the class, so I can access the variables.

```
from machine import I2C,Pin
import bmp280

i2c = machine.I2C(0,sda=Pin(20),scl=Pin(21))

bmp=bmp280.BMP280(i2c)
bmp.use_case(bmp280.BMP280_CASE_WEATHER)
bmp.oversample(bmp280.BMP280_OS_HIGH)
print("temp:{}".format(bmp.temperature))
print("pressure:{}".format(bmp.pressure))
```

**Comment by dafvid** [comment] 2021-03-07 10:51
Great to hear it's up and running.

I've updated the example code also. Closing this.

**Closed by dafvid** 2021-03-07 10:51 UTC

**Comment by BeardedBart** [comment] 2023-08-08 13:58
varna9000 code still does not working for me. 
In Thonny IDE, this error is shown:
![image](https://github.com/dafvid/micropython-bmp280/assets/77555309/8b29c398-6f12-4467-b2ed-865cb9d357fc)

I've checked 5 times the wiring and code; also in I2C scan the device is visible:
![image](https://github.com/dafvid/micropython-bmp280/assets/77555309/e0c6ba9c-959f-4cc3-b30b-d07ac27ccbc9)
(Do not mind 0x3c, it's an OLED screen)

**Comment by dafvid** [comment] 2023-08-08 14:02
HiTry adding a short sleep before connecting. Best is to not power the sensors via the board but directly. So that they have power before the board is started.See this link alsoOSError: [Errno 5] EIO while using I2C - MicroPython Forum (Archive)-DavidOn 8 Aug 2023, at 15:58, BeardedBart ***@***.***> wrote:varna9000 code still does not working for me. In Thonny IDE, this error is shown: —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by BeardedBart** [comment] 2023-08-08 14:26
Powering board directly is making device unvisible to I2C scan, power is delivered to Pi Pico through usb cable capable of outputting 2A max and with proper data connections available.

**Comment by BeardedBart** [comment] 2023-08-08 14:30
Okay, the issue was, as Mr. Stenwall said, with the power management. After connecting the Vcc and GND, both Pi Pico and sensors, issue was fixed.

**Comment by eMUQI** [comment] 2023-12-22 06:04
Recently, I've been struggling with the same issue. I've attempted all the methods mentioned above to resolve it, but none have proven effective.

After a period of searching, I eventually found both the root cause of the problem and its solution at https://forum.micropython.org/viewtopic.php?t=12997.

> [Re: bmp280 error ?](https://forum.micropython.org/viewtopic.php?t=12997#p70924)
>  by [iceelon](https://forum.micropython.org/memberlist.php?mode=viewprofile&u=10868&sid=7233d6c13155ef1bed53ee4235b71e83) » Tue Sep 13, 2022 10:27 am
> 
> ... thinking about it I found the error... it is silly... it turns out that the bmp280 manufactured after 2021 (by the serial id ) only work at frequencies of 100000 bus, if you lower it after a few readings it gives an error and if you raise it it does not get to read anything giving an error type device does not exist ....

I'm sharing this here in hopes that it might help others facing a similar issue.  Referring to the example provided by @varna9000, the final available code is as follows:

```python
from machine import I2C,Pin
import bmp280

i2c = machine.I2C(0,sda=Pin(20),scl=Pin(21), freq = 100000)

bmp=bmp280.BMP280(i2c)

bmp.use_case(bmp280.BMP280_CASE_WEATHER)
bmp.oversample(bmp280.BMP280_OS_HIGH)
print("temp:{}".format(bmp.temperature))
print("pressure:{}".format(bmp.pressure))
```
