### ISSUE TITLE
Typo in use_case argument to constructor?

### ISSUE THREAD

**Issue by strongbutgood** [dafvid/micropython-bmp280#4] opened 2022-03-15 05:14 UTC
https://github.com/dafvid/micropython-bmp280/blob/ff13a34cf7cd4424bb16f2387a29183689c302d2/bmp280.py#L122

Looking through the code base as I'm looking for a package that does what I expect I saw this line and wondered if it should read:
```py
        if use_case is not None:
            self.use_case(use_case)
```

I haven't tested either way yet, that is on the plan for tomorrow...

**EDIT:**
Apologies I didn't see #3 conversation. Will move to conversation on the PR.

**Comment by dafvid** [comment] 2022-03-15 05:32
Yes. Duplicate of #3.

**Closed** 2022-03-15 09:26 UTC
